// pdfReport.js — PDF report generation using jsPDF

const PDFReport = {
  /**
   * Generate a daily study list PDF (背诵清单).
   */
  async generateStudyList(dateStr) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const plan = await DB.db.get('dailyPlans', dateStr) || await Scheduler.generateDailyPlan(dateStr);

    // Title
    doc.setFontSize(18);
    doc.text('📖 今日背诵清单', 14, 20);
    doc.setFontSize(12);
    doc.text(`日期: ${dateStr}`, 14, 30);

    let y = 42;

    // New words section
    if (plan.newWords.length > 0) {
      doc.setFontSize(14);
      doc.setTextColor(74, 144, 217);
      doc.text('🆕 新词学习', 14, y);
      y += 10;

      for (const id of plan.newWords) {
        const w = await WordStore.get(id);
        if (!w) continue;
        y = this._drawWordRow(doc, w, y);
        if (y > 270) { doc.addPage(); y = 20; }
      }
    }

    // Review words section
    if (plan.reviewWords.length > 0) {
      y += 8;
      doc.setFontSize(14);
      doc.setTextColor(39, 174, 96);
      doc.text('🔄 复习巩固', 14, y);
      y += 10;

      for (const id of plan.reviewWords) {
        const w = await WordStore.get(id);
        if (!w) continue;
        y = this._drawWordRow(doc, w, y);
        if (y > 270) { doc.addPage(); y = 20; }
      }
    }

    // Stubborn words section
    if (plan.stubbornWords.length > 0) {
      y += 8;
      doc.setFontSize(14);
      doc.setTextColor(231, 76, 60);
      doc.text('🎯 专项攻克 (顽固词)', 14, y);
      y += 10;

      for (const id of plan.stubbornWords) {
        const w = await WordStore.get(id);
        if (!w) continue;
        y = this._drawWordRow(doc, w, y);
        if (y > 270) { doc.addPage(); y = 20; }
      }
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(127, 140, 141);
    doc.text('Generated by VocabTracker · 每天进步一点点', 14, 285);

    return doc;
  },

  /** Draw a single word row, return new y position */
  _drawWordRow(doc, word, y) {
    doc.setFontSize(11);
    doc.setTextColor(44, 62, 80);
    const posLabel = word.partOfSpeech ? `[${word.partOfSpeech}] ` : '';
    doc.text(`${word.spelling}  ${posLabel}${word.phonetic || ''}`, 14, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor(127, 140, 141);
    doc.text(`   ${word.meaning}`, 14, y);
    if (word.exampleSentence) {
      y += 6;
      doc.text(`   ${word.exampleSentence}`, 14, y);
    }
    y += 8;
    return y;
  },

  /**
   * Generate a quiz/test PDF (测试卷).
   */
  async generateQuizSheet(dateStr) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const plan = await DB.db.get('dailyPlans', dateStr) || await Scheduler.generateDailyPlan(dateStr);
    const allWordIds = [...plan.newWords, ...plan.reviewWords, ...plan.stubbornWords];
    const words = [];
    for (const id of allWordIds) {
      const w = await WordStore.get(id);
      if (w) words.push(w);
    }

    doc.setFontSize(18);
    doc.text('📝 单词测试卷', 14, 20);
    doc.setFontSize(12);
    doc.text(`日期: ${dateStr}    姓名: ________    得分: ________`, 14, 30);

    let y = 44;
    let qNum = 1;

    // Part A: 英译中 (multiple choice)
    doc.setFontSize(14);
    doc.setTextColor(74, 144, 217);
    doc.text('A. 英译中 (选择正确的释义)', 14, y);
    y += 10;

    for (const w of words) {
      const q = await QuizEngine.generateEnToCh(w);
      if (y > 260) { doc.addPage(); y = 20; }

      doc.setFontSize(11);
      doc.setTextColor(44, 62, 80);
      doc.text(`${qNum}. ${w.spelling}`, 14, y);
      y += 7;

      const letters = ['A', 'B', 'C', 'D'];
      for (let i = 0; i < q.options.length; i++) {
        doc.setFontSize(10);
        doc.text(`   ${letters[i]}. ${q.options[i]}`, 18, y);
        y += 6;
      }
      y += 4;
      qNum++;
    }

    // Part B: 中译英
    y += 8;
    doc.setFontSize(14);
    doc.setTextColor(39, 174, 96);
    doc.text('B. 中译英 (写出英文单词)', 14, y);
    y += 12;

    for (const w of words) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFontSize(11);
      doc.setTextColor(44, 62, 80);
      doc.text(`${qNum}. ${w.meaning}  __________________`, 14, y);
      y += 8;
      qNum++;
    }

    doc.setFontSize(10);
    doc.setTextColor(127, 140, 141);
    doc.text('Generated by VocabTracker · 每天进步一点点', 14, 285);

    return doc;
  },

  /** Save and download a PDF */
  downloadPDF(doc, filename) {
    doc.save(filename);
  },
};
